import type { BibleBook } from "./types";

export const bibleBooks: BibleBook[] = [
  { id: "genesis", name: "Genesis", abbreviation: "Gen", chapters: 50, testament: "old" },
  { id: "exodus", name: "Exodus", abbreviation: "Exod", chapters: 40, testament: "old" },
  { id: "leviticus", name: "Leviticus", abbreviation: "Lev", chapters: 27, testament: "old" },
  { id: "numbers", name: "Numbers", abbreviation: "Num", chapters: 36, testament: "old" },
  { id: "deuteronomy", name: "Deuteronomy", abbreviation: "Deut", chapters: 34, testament: "old" },
  { id: "joshua", name: "Joshua", abbreviation: "Josh", chapters: 24, testament: "old" },
  { id: "judges", name: "Judges", abbreviation: "Judg", chapters: 21, testament: "old" },
  { id: "ruth", name: "Ruth", abbreviation: "Ruth", chapters: 4, testament: "old" },
  { id: "1-samuel", name: "1 Samuel", abbreviation: "1 Sam", chapters: 31, testament: "old" },
  { id: "2-samuel", name: "2 Samuel", abbreviation: "2 Sam", chapters: 24, testament: "old" },
  { id: "1-kings", name: "1 Kings", abbreviation: "1 Kgs", chapters: 22, testament: "old" },
  { id: "2-kings", name: "2 Kings", abbreviation: "2 Kgs", chapters: 25, testament: "old" },
  { id: "1-chronicles", name: "1 Chronicles", abbreviation: "1 Chr", chapters: 29, testament: "old" },
  { id: "2-chronicles", name: "2 Chronicles", abbreviation: "2 Chr", chapters: 36, testament: "old" },
  { id: "ezra", name: "Ezra", abbreviation: "Ezra", chapters: 10, testament: "old" },
  { id: "nehemiah", name: "Nehemiah", abbreviation: "Neh", chapters: 13, testament: "old" },
  { id: "esther", name: "Esther", abbreviation: "Esth", chapters: 10, testament: "old" },
  { id: "job", name: "Job", abbreviation: "Job", chapters: 42, testament: "old" },
  { id: "psalms", name: "Psalms", abbreviation: "Ps", chapters: 150, testament: "old" },
  { id: "proverbs", name: "Proverbs", abbreviation: "Prov", chapters: 31, testament: "old" },
  { id: "ecclesiastes", name: "Ecclesiastes", abbreviation: "Eccl", chapters: 12, testament: "old" },
  { id: "song-of-solomon", name: "Song of Solomon", abbreviation: "Song", chapters: 8, testament: "old" },
  { id: "isaiah", name: "Isaiah", abbreviation: "Isa", chapters: 66, testament: "old" },
  { id: "jeremiah", name: "Jeremiah", abbreviation: "Jer", chapters: 52, testament: "old" },
  { id: "lamentations", name: "Lamentations", abbreviation: "Lam", chapters: 5, testament: "old" },
  { id: "ezekiel", name: "Ezekiel", abbreviation: "Ezek", chapters: 48, testament: "old" },
  { id: "daniel", name: "Daniel", abbreviation: "Dan", chapters: 12, testament: "old" },
  { id: "hosea", name: "Hosea", abbreviation: "Hos", chapters: 14, testament: "old" },
  { id: "joel", name: "Joel", abbreviation: "Joel", chapters: 3, testament: "old" },
  { id: "amos", name: "Amos", abbreviation: "Amos", chapters: 9, testament: "old" },
  { id: "obadiah", name: "Obadiah", abbreviation: "Obad", chapters: 1, testament: "old" },
  { id: "jonah", name: "Jonah", abbreviation: "Jonah", chapters: 4, testament: "old" },
  { id: "micah", name: "Micah", abbreviation: "Mic", chapters: 7, testament: "old" },
  { id: "nahum", name: "Nahum", abbreviation: "Nah", chapters: 3, testament: "old" },
  { id: "habakkuk", name: "Habakkuk", abbreviation: "Hab", chapters: 3, testament: "old" },
  { id: "zephaniah", name: "Zephaniah", abbreviation: "Zeph", chapters: 3, testament: "old" },
  { id: "haggai", name: "Haggai", abbreviation: "Hag", chapters: 2, testament: "old" },
  { id: "zechariah", name: "Zechariah", abbreviation: "Zech", chapters: 14, testament: "old" },
  { id: "malachi", name: "Malachi", abbreviation: "Mal", chapters: 4, testament: "old" },
  { id: "matthew", name: "Matthew", abbreviation: "Matt", chapters: 28, testament: "new" },
  { id: "mark", name: "Mark", abbreviation: "Mark", chapters: 16, testament: "new" },
  { id: "luke", name: "Luke", abbreviation: "Luke", chapters: 24, testament: "new" },
  { id: "john", name: "John", abbreviation: "John", chapters: 21, testament: "new" },
  { id: "acts", name: "Acts", abbreviation: "Acts", chapters: 28, testament: "new" },
  { id: "romans", name: "Romans", abbreviation: "Rom", chapters: 16, testament: "new" },
  { id: "1-corinthians", name: "1 Corinthians", abbreviation: "1 Cor", chapters: 16, testament: "new" },
  { id: "2-corinthians", name: "2 Corinthians", abbreviation: "2 Cor", chapters: 13, testament: "new" },
  { id: "galatians", name: "Galatians", abbreviation: "Gal", chapters: 6, testament: "new" },
  { id: "ephesians", name: "Ephesians", abbreviation: "Eph", chapters: 6, testament: "new" },
  { id: "philippians", name: "Philippians", abbreviation: "Phil", chapters: 4, testament: "new" },
  { id: "colossians", name: "Colossians", abbreviation: "Col", chapters: 4, testament: "new" },
  { id: "1-thessalonians", name: "1 Thessalonians", abbreviation: "1 Thess", chapters: 5, testament: "new" },
  { id: "2-thessalonians", name: "2 Thessalonians", abbreviation: "2 Thess", chapters: 3, testament: "new" },
  { id: "1-timothy", name: "1 Timothy", abbreviation: "1 Tim", chapters: 6, testament: "new" },
  { id: "2-timothy", name: "2 Timothy", abbreviation: "2 Tim", chapters: 4, testament: "new" },
  { id: "titus", name: "Titus", abbreviation: "Titus", chapters: 3, testament: "new" },
  { id: "philemon", name: "Philemon", abbreviation: "Phlm", chapters: 1, testament: "new" },
  { id: "hebrews", name: "Hebrews", abbreviation: "Heb", chapters: 13, testament: "new" },
  { id: "james", name: "James", abbreviation: "Jas", chapters: 5, testament: "new" },
  { id: "1-peter", name: "1 Peter", abbreviation: "1 Pet", chapters: 5, testament: "new" },
  { id: "2-peter", name: "2 Peter", abbreviation: "2 Pet", chapters: 3, testament: "new" },
  { id: "1-john", name: "1 John", abbreviation: "1 John", chapters: 5, testament: "new" },
  { id: "2-john", name: "2 John", abbreviation: "2 John", chapters: 1, testament: "new" },
  { id: "3-john", name: "3 John", abbreviation: "3 John", chapters: 1, testament: "new" },
  { id: "jude", name: "Jude", abbreviation: "Jude", chapters: 1, testament: "new" },
  { id: "revelation", name: "Revelation", abbreviation: "Rev", chapters: 22, testament: "new" },
];
